platform :ios, '9.0'
use_frameworks!

target 'ReactPoc' do
  pod 'Gigya-iOSSDK'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

end